test: verify stripe secret from branch fitur-krisna

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -2,9 +2,9 @@ name: Hotel Booking CI/CD - Kelompok 16 Week 4 Real Pipeline
 
 on:
   push:
-    branches: [ main ]
+    branches: [ fitur-krisna ]
   pull_request:
-    branches: [ main ]
+    branches: [ fitur-krisna ]
 
 jobs:
   pipeline-deployment:
@@ -39,7 +39,15 @@ jobs:
       run: |
         echo "Menjalankan automated testing unit untuk pengujian logika RBAC..."
         echo "Validasi Hak Akses Admin, Manager, dan Customer: PASSED!"
-
+        
+    - name: 🧪 UJI COBA: Cek Apakah GitHub Secret Terbaca
+      run: |
+        if [ -z "${{ secrets.STRIPE_WEB_PUB_KEY }}" ]; then
+          echo "❌ ERROR: GitHub Secret KOSONG! Periksa kembali penulisan nama di GitHub."
+          exit 1
+        else
+          echo "✅ SUKSES: GitHub Secret berhasil dideteksi dan siap disuntikkan ke Vite!"
+        fi
     # ==========================================
     # STAGE 3: BUILD & CONTAINERIZATION (LOCAL VALIDATION)
     # ==========================================
@@ -50,7 +58,10 @@ jobs:
       
     - name: 6.5 Validate Frontend Dockerfile Build
       run: |
-        docker build -f hotel-booking-frontend/Dockerfile -t hotel-booking-frontend:test .
+        docker build -f hotel-booking-frontend/Dockerfile \
+          --build-arg VITE_API_BASE_URL=http://localhost:5001 \
+          --build-arg VITE_STRIPE_PUBLISHABLE_KEY=pk_test_mock \
+          -t hotel-booking-frontend:test .
         echo "Docker build untuk frontend sukses divalidasi tanpa error!"
 
     # ==========================================
@@ -69,10 +80,10 @@ jobs:
         docker build -f hotel-booking-backend/Dockerfile -t kelompok16pso.azurecr.io/hotel-booking-backend:${{ github.sha }} .
         docker push kelompok16pso.azurecr.io/hotel-booking-backend:${{ github.sha }}
         
-        # 2. Build Frontend dengan menyuntikkan URL API DAN Kunci Stripe sekaligus via --build-arg
+        # 2. Build Frontend dengan nama variabel yang baru & kunci asli dari GitHub Secrets
         docker build -f hotel-booking-frontend/Dockerfile \
           --build-arg VITE_API_BASE_URL=https://kelompok16-hotel-backend-bugsabada3dpafb0.indonesiacentral-01.azurewebsites.net \
-          --build-arg VITE_STRIPE_PUB_KEY=pk_test_dummy12345 \
+          --build-arg VITE_STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_WEB_PUB_KEY }} \
           -t kelompok16pso.azurecr.io/hotel-booking-frontend:${{ github.sha }} .
         
         # 3. Push Frontend Image yang sudah lengkap (API + Stripe) ke Azure ACR
